eureka:
  client:
    serviceUrl:
      defaultZone       : http://localhost:9001/eureka/
server:
  port                  : 9002
#  port                  : 9003

spring:
  application:
    name                : eureka-service
  zipkin:
    base-url            : http://localhost:9006
  datasource:
    first:
      jdbcUrl           : jdbc:mysql://localhost:3306/test1?characterEncoding=utf-8&useSSL=true
      username          : root
      password          : 'root'
      driverClassName   : com.mysql.cj.jdbc.Driver
    second:
      jdbcUrl           : jdbc:mysql://localhost:3306/test2?characterEncoding=utf-8&useSSL=true
      username          : root
      password          : 'root'
      driverClassName   : com.mysql.cj.jdbc.Driver
  redis:
    host                : localhost
    port                : 6379
#    password            :
    timeout             : 10000
    lettuce:
      pool:
        max-active        : -1
        max-wait          : -1
        max-idle          : 10
        min-idle          : 0
